use_frameworks!

platform :ios, '13.0'

target 'IQKeyboardToolbarManager_Example' do
  pod 'IQTextView'
  pod 'IQKeyboardToolbarManager', :path => '../'

  target 'IQKeyboardToolbarManager_Tests' do
    inherit! :search_paths

  end
end
