use_frameworks!

platform :ios, '13.0'

target 'IQKeyboardToolbarManager_Example' do
  pod 'IQTextView'
  pod 'IQKeyboardToolbarManager', :path => '../'
  pod "SwiftLint"
end

target 'IQKeyboardToolbarManager_ObjcExample' do
  pod 'IQTextView'
  pod 'IQKeyboardToolbarManager', :path => '../'
end
